### ISSUE TITLE
Parse error for 2.2.3

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.ZFS#15]
Will track down the cause but noting this here for record-keeping - catching this error against a 2.2.3 built, packaged, and installed on Ubuntu 22.04. May happen on others, will check Arch shortly:
```
2024-03-26 23:38:57,653 ERROR zen.ZenModeler: Traceback (most recent call last):
  File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 669, in processClient
    datamaps = plugin.process(device, results, self.log)
  File "/opt/zenoss/ZenPacks/ZenPacks.daviswr.ZFS-0.8.0-py2.7.egg/ZenPacks/daviswr/ZFS/modeler/plugins/daviswr/cmd/ZFS.py", line 200, in process
    comp[key] = int(datasets[ds][key])
ValueError: invalid literal for int() with base 10: 'none'
```

**Comment by daviswr** [comment]
I've recreated this on Debian 12 with 2.2.3, will check into it

**Comment by daviswr** [comment]
Found the culprit:

On 2.0.3, for example, zfs get returned a huge number for filesystem/snapshot count/limit to reflect effectively no limit. In 2.2.3, at least, zfs get now returns the string "none".

```
$ zfs get -pH all pool0 | grep -e limit -e count
pool0	filesystem_limit	18446744073709551615	default
pool0	snapshot_limit	18446744073709551615	default
pool0	filesystem_count	18446744073709551615	default
pool0	snapshot_count	18446744073709551615	default
```
vs
```
$ zfs get -pH all vmpool | grep -e limit -e count
vmpool	filesystem_limit	none	default
vmpool	snapshot_limit	none	default
vmpool	filesystem_count	none	default
vmpool	snapshot_count	none	default
```

Interestingly, when -p is omitted on 2.0.3, it reports "none" for the field.

Not too bad to handle.
